// ===== SIEVENT — Panel Admin (W-10 s/d W-18) =====
let PS=0,AD={},KID='',LP=0,LAST={h:[],r:[],n:'data'},QS=[];
const A=(a,d)=>{window.__adt=0;return post(a,{...d,token:sessionStorage.tk})},pill=(t,c)=>`<span class="pill ${c}">${esc(t)}</span>`,stt=e=>e.draf?['Draf','amber']:(BADGE[e.status]||BADGE.Tutup),kn=id=>(AD.kegiatan.find(k=>k.id==id)||{}).nama||'-';
const ksel=()=>`<select style="max-width:380px;margin:8px 0" onchange="KID=this.value;admin(location.hash.split('/')[2])">${AD.kegiatan.map(k=>`<option value="${k.id}" ${k.id==KID?'selected':''}>${esc(k.nama)}</option>`).join('')}</select>`;
const tbl=(h,r)=>`<div style="overflow:auto"><table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${r.map(x=>`<tr>${x.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${h.length}" class="mut center">Belum ada data</td></tr>`}</table></div>`;
function csv(h,r,n){const t=[h,...r].map(x=>x.map(c=>`"${String(c).replace(/<[^>]*>/g,'').replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+t],{type:'text/csv'}));a.download=n+'.csv';a.click()}
async function act(a,d,v){const r=await A(a,d);toast(r.message||'OK',r.success?'':'err');if(r.success){document.querySelector('.modal')?.remove();admin(v)}}
function ask(t,fn,l='Ya, lanjutkan'){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="card"><div class="tick rd">!</div><p>${t}</p><div class="row"><button class="btn ghost" onclick="this.closest('.modal').remove()">Batal</button><button class="btn" style="background:#EF4444" id="ya">${l}</button></div></div></div>`);$('#ya').onclick=async()=>{$('.modal').remove();await fn()}}
function mdl(t,body,fn,l='Simpan'){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><form class="card" id="mf" style="text-align:left;width:min(480px,92vw)"><h3>${t}</h3>${body}<div class="row" style="margin-top:16px"><button type="button" class="btn ghost" onclick="this.closest('.modal').remove()">Batal</button><button class="btn">${l}</button></div></form></div>`);$('#mf').onsubmit=async ev=>{ev.preventDefault();await fn(fd(ev.target))}}
const opt=(l,s)=>l.map(x=>`<option ${x===s?'selected':''}>${esc(x)}</option>`).join('');
function addP(){mdl('Tambah Peserta Manual',`<label>Kegiatan</label><select name="id_kegiatan">${AD.kegiatan.map(k=>`<option value="${k.id}">${esc(k.nama)}</option>`).join('')}</select><label>Nama Lengkap & Gelar</label><input name="nama_lengkap" required><label>Email</label><input type="email" name="email" required><label>Asal Instansi</label><input name="asal_instansi"><label>No HP</label><input name="no_hp"><label>Kabupaten / Kota</label><select name="kabupaten_kota">${opt(KAB)}</select>`,p=>act('aPeserta',{op:'add',p},'peserta'))}
function editQ(i){const q=QS[i]||{};mdl(i==null?'Tambah Pertanyaan':'Ubah Pertanyaan',`<label>Teks Pertanyaan</label><textarea name="teks_pertanyaan" required>${esc(q.teks_pertanyaan||'')}</textarea><label>Tipe</label><select name="tipe">${opt(['Skala 1-5','Rating Bintang','Pilihan','Teks'],q.tipe)}</select><label>Opsi (pisahkan dengan |, untuk tipe Pilihan)</label><input name="opsi" value="${esc(q.opsi||'')}"><label>Urutan</label><input type="number" name="urutan" value="${q.urutan||QS.length+1}"><label class="opt"><input type="checkbox" name="wajib" ${q.id_pertanyaan==null||String(q.wajib).toUpperCase()==='TRUE'?'checked':''}> Wajib diisi</label>`,d=>act('aQuestion',{op:'save',q:{...d,wajib:!!d.wajib,id_kegiatan:KID,id_pertanyaan:q.id_pertanyaan}},'evaluasi'))}
function salinQ(){if(AD.kegiatan.length<2)return toast('Belum ada kegiatan lain untuk disalin','err');mdl('Salin Pertanyaan dari Kegiatan Lain',`<div class="info amber">Pertanyaan pada kegiatan ini akan <b>diganti</b> dengan pertanyaan dari kegiatan sumber.</div><label>Sumber</label><select name="dari">${AD.kegiatan.filter(k=>k.id!=KID).map(k=>`<option value="${k.id}">${esc(k.nama)}</option>`).join('')}</select>`,d=>act('aQuestion',{op:'copy',dari:d.dari,id_kegiatan:KID},'evaluasi'))}
async function saveEv(ev){ev.preventDefault();const b=ev.submitter,f=ev.target,e=fd(f);e.status=b.value;const fl=f.gambar.files[0];delete e.gambar;
if(e.sumber_gambar==='Link')e.url_gambar=e.link_gambar;else if(fl){const z=await comp(fl);e.gambar_b64=z.b;e.gambar_tipe=z.t;e.gambar_nama='cover.'+(z.t==='image/webp'?'webp':'jpg')}
b.disabled=true;const r=await A('aSaveEvent',{e});b.disabled=false;toast(r.message,r.success?'':'err');if(r.success)location.hash='#/admin/kegiatan'}
function cfgSave(ev){ev.preventDefault();const{pb,...c}=fd(ev.target);if(ev.target.pb)c.IZINKAN_PEMBATALAN=pb?'Y':'N';act('aConfig',{c},'pengaturan')}
const prow=p=>{const a=p.status_pendaftaran==='Terdaftar';return[`<b class="av" data-i="${esc(String(p.nama_lengkap).trim().slice(0,2).toUpperCase())}">${esc(p.nama_lengkap)}</b>`,`${esc(p.email)}<br><small class="mut">${esc(p.no_hp)}</small>`,`${esc(p.asal_instansi)}<br>${pill(p.kabupaten_kota,'gray')}`,esc(kn(p.id_kegiatan)),pill(p.status_pendaftaran,a?'green':p.status_pendaftaran==='Waiting'?'amber':'gray'),p.status_pendaftaran!=='Batal'?`<a style="color:#EF4444;cursor:pointer" onclick="ask('Batalkan pendaftaran peserta ini? Kuota akan dibebaskan.',()=>act('aPeserta',{op:'cancel',id:'${p.id}'},'peserta'),'Batalkan')">Batalkan</a>`:'']};
const st4=l=>`<div class="stats">${l.map(([a,b,c,d])=>`<div class="card pad stat"><span class="ico">${d||''}</span><small>${a}</small><b>${b}</b><small>${c||''}</small></div>`).join('')}</div>`;
const V={
dashboard:()=>{const s=AD.stats,pend=AD.sertifikat.filter(x=>x.status==='Terbit'&&!x.pdf).length,col=['#064E3B','#059669','#F59E0B','#34D399','#A7F3D0','#9CA3AF'],tot=AD.perKab.reduce((a,x)=>a+x.jumlah,0)||1;let acc=0;
const grad=AD.perKab.map((x,i)=>{const a=acc/tot*100;acc+=x.jumlah;return `${col[i%6]} ${a}% ${acc/tot*100}%`}).join(',')||'#E5E7EB 0 100%';
return `<h1>Selamat Datang, Administrator 👋</h1><p class="mut">Pantau kegiatan bimtek, kehadiran presensi WITA, dan otomatisasi sertifikat.</p>${pend?`<div class="card pad amber" style="border-left:4px solid var(--g)"><b>PERHATIAN E-SERTIFIKAT</b><br>${pend} e-sertifikat menunggu diproses. <a href="#/admin/sertifikat" style="color:var(--p);font-weight:600">Tinjau antrean →</a></div>`:''}${st4([['Kegiatan Terdaftar',s.kegiatan,'Sesi Agenda','📅'],['Peserta Seluruh Kaltim',s.peserta,'Peserta','👥'],['Tingkat Kehadiran Valid',s.hadir+'%','WITA Lock','⏱'],['Sertifikat Tervalidasi',s.sertifikat,'Lembar','🛡']])}<div class="two"><div class="card pad"><h3>Tren Partisipasi Peserta per Kegiatan</h3>${AD.perKegiatan.map(k=>`<div class="row"><span>${esc(k.nama)}</span><b>${k.terisi}/${k.kuota}</b></div><div class="bar"><i style="width:${Math.min(100,k.terisi/(k.kuota||1)*100)}%"></i></div>`).join('')}</div><div class="card pad"><h3>Sebaran Peserta per Kab/Kota</h3><div class="donut" style="background:conic-gradient(${grad})"><span>${tot}</span></div>${AD.perKab.map((x,i)=>`<div class="lg"><span><i style="background:${col[i%6]}"></i>${esc(x.nama)}</span><b>${x.jumlah}</b></div>`).join('')}</div></div><div class="two" style="margin-top:16px"><div class="card pad"><h3>Kegiatan Berlangsung & Paling Terkini</h3>${tbl(['Kegiatan','Jadwal','Kuota'],AD.kegiatan.filter(e=>!e.draf&&e.status!=='Selesai').slice(0,5).map(e=>[`<b>${esc(e.nama)}</b><br>${pill(e.mode,'gray')} <small class="mut">${esc(e.tempat)}</small>`,esc(e.tanggal),`${e.terisi}/${e.kuota}`]))}</div><div class="card pad"><h3>● Pusat Log Sistem</h3><small class="mut">Aktivitas terbaru: pendaftaran, presensi, sertifikat</small>${(AD.log||[]).map(l=>`<div class="info"><small class="mut">${esc(l.t)} WITA</small><br>${esc(l.x)}</div>`).join('')||'<p class="mut">Belum ada aktivitas.</p>'}</div></div>`},
kegiatan:()=>{const rowK=e=>{const[b,c]=stt(e);return[`<b>${esc(e.nama)}</b><br>${pill(e.kategori,'green')} ${pill(e.mode,'gray')}`,esc(e.tanggal),`${e.terisi}/${e.kuota}<div class="bar"><i style="width:${Math.min(100,e.terisi/(e.kuota||1)*100)}%"></i></div>`,pill(b,c),`<a title="Ubah" href="#/admin/form/${e.id}">✏</a> <a title="Duplikat" style="cursor:pointer" onclick="act('aEvent',{op:'duplikat',id:'${e.id}'},'kegiatan')">⧉</a> <a title="Arsipkan" style="cursor:pointer" onclick="act('aEvent',{op:'arsip',id:'${e.id}'},'kegiatan')">🗄</a> <a title="Hapus" style="cursor:pointer;color:#EF4444" onclick="ask('Hapus kegiatan ini secara permanen?',()=>act('aEvent',{op:'hapus',id:'${e.id}'},'kegiatan'),'Hapus')">🗑</a>`]};
window.kf=t=>{const r=AD.kegiatan.filter(e=>t==='Semua'||(t==='Draf'?e.draf:t==='Pendaftaran Dibuka'?!e.draf&&e.status==='Buka':!e.draf&&e.status==='Selesai'));$('#kt').innerHTML=tbl(['Kegiatan','Jadwal (WITA)','Kuota','Status','Aksi'],r.map(rowK));document.querySelectorAll('#ktabs a').forEach(x=>x.className=x.dataset.t===t?'on':'')};setTimeout(()=>kf('Semua'));
const s=AD.stats,occ=Math.round(AD.kegiatan.reduce((x,e)=>x+e.terisi/(e.kuota||1),0)/(AD.kegiatan.length||1)*100);
return `<div class="row"><div><h1>Kelola & Manajemen Kegiatan</h1><p class="mut">Status publikasi, kuota, dan jendela waktu otomatis (WITA).</p></div><a class="btn gold" href="#/admin/form">+ Tambah Kegiatan Baru</a></div>${st4([['Total Kegiatan',s.kegiatan,'Sesi terdaftar','📅'],['Pendaftar Aktif',s.peserta,'Peserta','👥'],['Rata-rata Okupansi',occ+'%','Kapasitas','📊'],['Sertifikat Terbit',s.sertifikat,'Dokumen sah','🏅']])}<div class="card pad"><div class="tabs" id="ktabs">${['Semua','Pendaftaran Dibuka','Draf','Selesai'].map(t=>`<a data-t="${t}" onclick="kf('${t}')">${t}</a>`).join('')}</div><div id="kt"></div></div>`},
form:id=>{const e=(AD.kegiatan.find(k=>k.id==id)||{}).raw||{},v=k=>esc(e[k]??'');setTimeout(tpl);
return `<form id="ef" onsubmit="saveEv(event)" oninput="tpl()" onchange="tpl()"><input type="hidden" name="id_kegiatan" value="${v('id_kegiatan')}"><input type="hidden" name="url_gambar" value="${v('url_gambar')}"><div class="row"><h1>${id?'Ubah Kegiatan':'Buat Kegiatan Baru'}</h1><a class="btn ghost" href="#/admin/kegiatan">Batal / Kembali</a></div>
<div class="sec">01 · Informasi Utama Kegiatan</div><div class="card pad"><label>Nama Kegiatan *</label><input name="nama_kegiatan" required value="${v('nama_kegiatan')}"><label>Kategori *</label><div class="g3">${['Bimtek','Sosialisasi','Workshop'].map(k=>`<label class="opt"><input type="radio" name="kategori" value="${k}" ${e.kategori===k||(!e.kategori&&k==='Bimtek')?'checked':''}> <b>${k}</b></label>`).join('')}</div><label>Deskripsi *</label><textarea name="deskripsi" rows="4" required>${v('deskripsi')}</textarea><div class="f2"><div><label>Mode Pelaksanaan *</label><select name="mode">${opt(['Offline','Online','Hybrid'],e.mode)}</select></div><div><label>Lokasi / Tempat *</label><input name="tempat" required value="${v('tempat')}"></div></div><label>Narasumber & Fasilitator (satu per baris: Nama — Jabatan)</label><textarea name="narasumber" rows="3">${v('narasumber')}</textarea><label>Link Pertemuan Online</label><input name="link_online" value="${v('link_online')}"><label>Cover Banner (rasio 16:9)</label><label class="opt"><input type="radio" name="sumber_gambar" value="Upload" checked> Unggah ke Google Drive <input type="file" name="gambar" accept="image/*" style="margin-top:6px"></label><label class="opt" style="margin-top:8px"><input type="radio" name="sumber_gambar" value="Link"> Tautkan gambar eksternal <input name="link_gambar" placeholder="https://..." value="${v('url_gambar')}" style="margin-top:6px"></label></div>
<div class="sec">02 · Jadwal & Kontrol Waktu Otomatis (WITA)</div><div class="card pad"><div class="f2"><div><label>Tanggal Mulai *</label><input type="date" name="tanggal_mulai" required value="${v('tanggal_mulai')}"></div><div><label>Tanggal Selesai *</label><input type="date" name="tanggal_selesai" required value="${v('tanggal_selesai')}"></div></div><label>Jam Pelaksanaan *</label><input name="jam" required placeholder="08:30 WITA" value="${v('jam')}"><div class="f2"><div class="info"><b>Jendela Pendaftaran</b><label>Buka</label><input type="datetime-local" name="daftar_buka" required value="${v('daftar_buka')}"><label>Tutup</label><input type="datetime-local" name="daftar_tutup" required value="${v('daftar_tutup')}"></div><div class="info"><b>Jendela Presensi (Hari-H)</b><label>Buka</label><input type="datetime-local" name="presensi_buka" required value="${v('presensi_buka')}"><label>Tutup</label><input type="datetime-local" name="presensi_tutup" required value="${v('presensi_tutup')}"></div></div><label>Batas Kuota Peserta *</label><input type="number" min="1" name="kuota" required value="${v('kuota')}"></div>
<div class="sec">03 · Template E-Sertifikat (Wajib Landscape)</div><div class="card pad"><div class="info amber">⚠ <b>Ketentuan wajib landscape.</b> Template portrait ditolak otomatis saat disimpan.</div><div class="f2"><label class="opt"><input type="radio" name="sumber_template_sertifikat" value="Default" ${e.link_template?'':'checked'}> <b>Template Standar SIEVENT</b><br><small class="mut">Memakai template default dari Pengaturan</small></label><label class="opt"><input type="radio" name="sumber_template_sertifikat" value="Link" ${e.link_template?'checked':''}> <b>Tautkan Google Slides Kustom</b><input name="link_template" placeholder="https://docs.google.com/presentation/d/..." value="${v('link_template')}" style="margin-top:6px"></label></div><p>Placeholder wajib: ${['{{nama}}','{{kegiatan}}','{{tanggal}}','{{nomor}}','{{kode}}'].map(x=>`<code>${x}</code>`).join(' ')}</p><div id="tpv" style="margin-top:12px"></div></div>
<div class="bar2"><button class="btn ghost" name="s" value="Draf">Simpan sebagai Draf</button><button class="btn" name="s" value="Terbit">Publikasikan (Terbit)</button></div></form>`},
peserta:()=>{const H=['Nama','Kontak','Instansi & Wilayah','Kegiatan','Status','Aksi'],ak=AD.peserta.filter(p=>p.status_pendaftaran==='Terdaftar').length;
window.pf=()=>{const q=$('#pq').value.toLowerCase(),k=$('#pk').value,r=AD.peserta.filter(p=>(!k||p.id_kegiatan==k)&&(!$('#ps').value||p.status_pendaftaran===$('#ps').value)&&(p.nama_lengkap+p.email+p.asal_instansi).toLowerCase().includes(q)).map(prow);LAST={h:H.slice(0,5),r:r.map(x=>x.slice(0,5)),n:'peserta'};$('#pt').innerHTML=tbl(H,r.slice(0,100))+(r.length>100?`<p class="cap">Menampilkan 100 dari ${r.length} — persempit dengan pencarian atau filter (ekspor tetap memuat semua).</p>`:'')};setTimeout(pf);
return `<div class="row"><h1>Manajemen Peserta Kegiatan</h1><span><button class="btn ghost" onclick="bcast()">📣 Broadcast</button> <button class="btn ghost" onclick="xlsx(LAST.h,LAST.r,LAST.n).catch(e=>toast(e.message,'err'))">Ekspor Excel</button> <button class="btn ghost" onclick="csv(LAST.h,LAST.r,LAST.n)">CSV</button> <button class="btn gold" onclick="addP()">+ Tambah Peserta Manual</button></span></div>${st4([['Total Pendaftar',AD.peserta.length,'Orang'],['Terdaftar Aktif',ak,'Peserta'],['Waiting List',AD.peserta.filter(p=>p.status_pendaftaran==='Waiting').length,'Antrean','⏳'],['Dibatalkan',AD.peserta.filter(p=>p.status_pendaftaran==='Batal').length,'Kuota terbebas','✖']])}<div class="card pad filters" style="grid-template-columns:2fr 1fr 1fr"><input id="pq" oninput="pf()" placeholder="🔍 Cari nama, email, instansi..."><select id="pk" onchange="pf()"><option value="">Semua Kegiatan</option>${AD.kegiatan.map(k=>`<option value="${k.id}">${esc(k.nama)}</option>`).join('')}</select><select id="ps" onchange="pf()"><option value="">Semua Status</option><option>Terdaftar</option><option>Waiting</option><option>Batal</option></select></div><div class="card pad" id="pt" style="margin-top:12px"></div>`},
presensi:()=>{const L=AD.peserta.filter(p=>p.id_kegiatan==KID&&p.status_pendaftaran==='Terdaftar'),h=L.filter(p=>p.hadir).length,pc=L.length?Math.round(h/L.length*1000)/10:0;
return `<h1>Presensi & Monitoring Kehadiran</h1>${ksel()}<div class="two" style="margin-top:12px"><div class="card pad center"><b>Tingkat Kehadiran</b><div class="gauge" style="background:conic-gradient(var(--p) ${pc}%,var(--b) 0)"><span>${pc}%</span></div><p class="mut">${h} dari ${L.length} peserta · ambang sertifikat 80%</p></div>${st4([['Hadir Valid',h,'Orang'],['Belum Hadir',L.length-h,'Orang']])}</div><div class="card pad" style="margin-top:16px">${tbl(['Nama & Instansi','Waktu Stempel (WITA)','Status Kehadiran','Aksi'],L.map(p=>[`<b>${esc(p.nama_lengkap)}</b><br><small class="mut">${esc(p.asal_instansi)}</small>`,p.waktu?`<code>${esc(p.waktu)}</code>`:'—',p.hadir?pill('HADIR VALID','green'):pill('BELUM HADIR','gray'),p.hadir?'':`<a style="color:var(--p);cursor:pointer;font-weight:600" onclick="ovr('${p.id}')">Tandai Hadir</a>`]))}</div><div class="two" style="margin-top:16px"><div class="card pad"><h3>▣ Kiosk QR Meja Luring</h3><p class="mut">Tampilkan layar QR di meja registrasi. Peserta memindai dengan ponsel dan langsung masuk ke halaman presensi.</p><a class="btn" target="_blank" href="#/kiosk/${KID}">Buka Layar Kiosk</a></div><div class="card pad"><h3>⬆ Impor Kehadiran Zoom</h3><p class="mut">Unggah laporan peserta Zoom (CSV). Email yang cocok dengan peserta terdaftar ditandai hadir.</p><input type="file" accept=".csv,.txt" onchange="imporZoom(this)"></div></div>`},
evaluasi:async()=>{const Q=(await get('getQuestions',{id:KID})).data||[],e=AD.evaluasi[KID]||{responden:0,avg:0,komentar:[]},seed=Q[0]&&/^q\d$/.test(Q[0].id_pertanyaan);QS=Q;
return `<div class="row"><h1>Kelola Evaluasi & Kuesioner</h1><button class="btn ghost" onclick="salinQ()">Salin dari Kegiatan Lain</button></div>${ksel()}${st4([['Rata-rata Skor',e.avg+' / 5.0'],['Responden',e.responden,'Orang'],['Butir Pertanyaan',Q.length]])}<div class="two"><div><h3>Daftar Butir Instrumen</h3>${seed?`<div class="info amber">Kegiatan ini memakai pertanyaan standar. <button class="btn" onclick="act('aQuestion',{op:'seed',id_kegiatan:'${KID}'},'evaluasi')">Salin untuk diedit</button></div>`:''}${Q.map((q,i)=>`<div class="card pad" style="margin-bottom:8px"><span class="pill green">${esc(q.tipe)}</span> ${String(q.wajib).toUpperCase()==='TRUE'?pill('Wajib','amber'):''}<p><b>${q.urutan}. ${esc(q.teks_pertanyaan)}</b></p>${seed?'':`<a style="cursor:pointer" onclick="editQ(${i})">✏ Ubah</a> &nbsp; <a style="cursor:pointer;color:#EF4444" onclick="ask('Hapus pertanyaan ini?',()=>act('aQuestion',{op:'del',id:'${q.id_pertanyaan}'},'evaluasi'),'Hapus')">🗑 Hapus</a>`}</div>`).join('')}${seed?'':'<button class="btn full ghost" onclick="editQ()">+ Tambah Pertanyaan Baru</button>'}</div><div class="card pad"><h3>Rekapitulasi Respons</h3><p>⭐ <b>${e.avg}</b> dari ${e.responden} responden</p><h3>Saran & Masukan Terbaru</h3>${(e.komentar||[]).map(k=>`<div class="info">“${esc(k)}”</div>`).join('')||'<p class="mut">Belum ada komentar.</p>'}</div></div>`},
sertifikat:()=>{const S=AD.sertifikat.filter(s=>s.id_kegiatan==KID),tb=S.filter(s=>s.status==='Terbit'),pend=tb.filter(s=>!s.pdf||s.kirim!=='Y').length;
return `<div class="row"><h1>Manajemen Penerbitan E-Sertifikat</h1><button class="btn gold" onclick="act('aProses',{},'sertifikat')">⚙ Proses Batch Sekarang</button></div><p class="mut">Sertifikat landscape dibuat & dikirim bertahap otomatis tiap 10 menit (hemat kuota email harian).</p>${ksel()}${st4([['Terbit',tb.length,'Lembar'],['Menunggu PDF / Email',pend,'Peserta'],['Dicabut',S.length-tb.length,'Dokumen']])}<div class="card pad">${tbl(['Peserta','Nomor & Kode','Terbit (WITA)','PDF / Email','Status','Aksi'],S.map(s=>[`<b>${esc(s.nama)}</b>`,`<span class="qr mini" data-q="${esc(s.kode)}"></span>${esc(s.nomor)}<br><code>${esc(s.kode)}</code>`,esc(s.tanggal),`${s.pdf?'📄':'⏳'} / ${s.kirim==='Y'?'✉ Terkirim':'Belum'}`,pill(s.status,s.status==='Terbit'?'green':'red'),s.status==='Terbit'?`<a style="cursor:pointer" onclick="act('aRevoke',{op:'resend',id:'${s.id}'},'sertifikat')">Kirim Ulang</a> · <a style="cursor:pointer;color:#EF4444" onclick="ask('Cabut sertifikat ini? Kode verifikasi akan berstatus DICABUT.',()=>act('aRevoke',{op:'revoke',id:'${s.id}'},'sertifikat'),'Cabut')">Cabut</a>`:`<a style="cursor:pointer" onclick="act('aRevoke',{op:'restore',id:'${s.id}'},'sertifikat')">Pulihkan</a>`]))}</div>`},
laporan:()=>{const T=['Rekap Kegiatan','Presensi','Evaluasi','Sertifikat'];let h,r;
if(LP==0){h=['Kegiatan','Kuota','Terdaftar','Hadir','% Hadir','Sertifikat'];r=AD.kegiatan.map(k=>{const L=AD.peserta.filter(p=>p.id_kegiatan==k.id&&p.status_pendaftaran==='Terdaftar'),hd=L.filter(p=>p.hadir).length;return[k.nama,k.kuota,L.length,hd,(L.length?Math.round(hd/L.length*100):0)+'%',AD.sertifikat.filter(s=>s.id_kegiatan==k.id&&s.status==='Terbit').length]})}
else if(LP==1){h=['Nama','Email','Instansi','Kab/Kota','Kehadiran'];r=AD.peserta.filter(p=>p.id_kegiatan==KID&&p.status_pendaftaran==='Terdaftar').map(p=>[p.nama_lengkap,p.email,p.asal_instansi,p.kabupaten_kota,p.hadir?'Hadir':'Belum hadir'])}
else if(LP==2){h=['Kegiatan','Responden','Skor Rata-rata (1-5)'];r=AD.kegiatan.map(k=>{const e=AD.evaluasi[k.id]||{};return[k.nama,e.responden||0,e.avg||0]})}
else{h=['Nomor','Kode','Nama','Status','Terbit (WITA)','Email'];r=AD.sertifikat.filter(s=>s.id_kegiatan==KID).map(s=>[s.nomor,s.kode,s.nama,s.status,s.tanggal,s.kirim])}
LAST={h,r,n:'laporan-'+T[LP].toLowerCase().replace(/ /g,'-')};
return `<div class="row"><h1>Laporan & Ekspor Terpadu</h1><span><button class="btn gold" onclick="xlsx(LAST.h,LAST.r,LAST.n).catch(e=>toast(e.message,'err'))">⬇ Unduh Excel (.xlsx)</button> <button class="btn ghost" onclick="csv(LAST.h,LAST.r,LAST.n)">Ekspor CSV</button></span></div><div class="tabs">${T.map((t,i)=>`<a class="${i==LP?'on':''}" onclick="LP=${i};admin('laporan')">${t}</a>`).join('')}</div>${LP==0||LP==2?'':ksel()}${st4([['Total Rekod',AD.peserta.length,'Peserta','👥'],['Rata-rata Kehadiran',AD.stats.hadir+'%','WITA match','⏱'],['Rata-rata Skor Evaluasi',AD.stats.skor+' / 5.0','Skala 1–5','⭐'],['Sertifikat Diterbitkan',AD.stats.sertifikat,'Dokumen sah','🏅']])}<div class="card pad">${tbl(h,r.map(x=>x.map(esc)))}</div><div class="card pad" style="margin-top:16px"><h3>🗘 Otomatisasi Laporan Berkala (Google Drive)</h3><p class="mut">Setiap Jumat 17:00 rekap kegiatan dibuat sebagai Google Sheets di folder <code>Laporan Berkala</code> dan, jika diisi, dikirim ke email berikut. Pastikan zona waktu proyek Apps Script = Asia/Makassar.</p><label class="opt"><input type="checkbox" id="lbOn" ${(AD.config||{}).LAPORAN_BERKALA==='Y'?'checked':''}> Aktifkan jadwal Jumat 17:00</label><input id="lbEm" type="email" placeholder="Email penerima ringkasan (opsional)" value="${esc((AD.config||{}).EMAIL_LAPORAN||'')}"><div style="margin-top:8px"><button class="btn" onclick="act('aLaporan',{op:'jadwal',aktif:$('#lbOn').checked,email:$('#lbEm').value},'laporan')">Simpan Jadwal</button> <button class="btn ghost" onclick="act('aLaporan',{op:'jalankan'},'laporan')">Sinkronisasi Sekarang</button></div></div>`},
pengaturan:()=>{const c=AD.config||{},T=['Identitas Platform','Database & Google','Parameter E-Sertifikat','Manajemen Admin','Keamanan & Zona Waktu'],inp=(n,l)=>`<label>${l}</label><input name="${n}" value="${esc(c[n]||'')}">`,
adm=`<div class="row"><h3>Manajemen Akun Administrator</h3><button class="btn" onclick="addAdm()">+ Tambah Akun Admin</button></div>${tbl(['Nama','Username','Status','Aksi'],(AD.admins||[]).map(a=>[esc(a.nama),`<code>${esc(a.username)}</code>`,pill(a.aktif?'Aktif':'Nonaktif',a.aktif?'green':'gray'),a.username===AD.me?'<small class="mut">(Anda)</small>':`<a style="cursor:pointer" onclick="act('aAdmin',{op:'toggle',username:'${esc(a.username)}'},'pengaturan')">${a.aktif?'Nonaktifkan':'Aktifkan'}</a>`]))}<form style="margin-top:16px" onsubmit="event.preventDefault();act('aPassword',fd(event.target),'pengaturan')"><h3>Ganti Kata Sandi Admin</h3><label>Kata sandi saat ini</label><input type="password" name="lama" required><label>Kata sandi baru (min. 8 karakter)</label><input type="password" name="baru" required><label>Ulangi kata sandi baru</label><input type="password" name="ulang" required><button class="btn" style="margin-top:12px">Ganti Kata Sandi</button></form>`,
sec=[`<h3>Identitas & Branding Instansi</h3><form onsubmit="cfgSave(event)">${inp('NAMA_APLIKASI','Nama Aplikasi')}${inp('EMAIL_PENGIRIM_NAMA','Nama Pengirim Email')}<button class="btn" style="margin-top:12px">Simpan Perubahan</button></form>`,
`<h3>Integrasi Google Drive & Spreadsheet</h3><p class="mut">ID Spreadsheet: <code>${esc(c.SPREADSHEET_ID||'-')}</code><br>ID Folder Drive: <code>${esc(c.ROOT_FOLDER_ID||'-')}</code></p><button class="btn ghost" onclick="act('aSistem',{op:'uji'},'pengaturan')">Uji Koneksi Workspace</button>`,
`<h3>Parameter Baku E-Sertifikat</h3><form onsubmit="cfgSave(event)">${inp('FORMAT_NOMOR','Format Nomor Sertifikat')}<small class="mut">Contoh: {NOMOR}/BMTK/{BULAN}/{TAHUN}</small>${inp('TEMPLATE_DEFAULT_ID','Template Default (link Google Slides landscape — kosong = template standar otomatis)')}<label class="opt" style="margin-top:12px"><input type="checkbox" name="pb" ${(c.IZINKAN_PEMBATALAN||'Y')!=='N'?'checked':''}> Izinkan peserta membatalkan pendaftaran</label><button class="btn" style="margin-top:12px">Simpan Perubahan</button></form>`,adm,
`<h3>Keamanan & Zona Waktu Server</h3>${[['Zona waktu operasional','Asia/Makassar (WITA, UTC+8)'],['Batas percobaan login','5 kali gagal → dikunci 15 menit'],['Masa sesi administrator','60 menit']].map(([a,b])=>`<div class="info"><small class="mut">${a}</small><br><b>${b}</b></div>`).join('')}`],
dz=`<h3 style="color:#EF4444">⚠ Zona Bahaya (Danger Zone)</h3><div class="info" style="background:#FEE2E2;color:#991B1B">Tindakan berikut berdampak langsung pada pemrosesan sertifikat dan struktur database.</div>${[['Hentikan pemrosesan sertifikat otomatis','Menghapus alarm 10 menit; sertifikat baru tidak dibuat/dikirim sampai diaktifkan lagi.','proses_off','Hentikan'],['Aktifkan pemrosesan sertifikat otomatis','Memasang kembali alarm 10 menit.','proses_on','Aktifkan'],['Sinkronisasi ulang struktur Google Sheets','Membuat sheet/kolom yang hilang sesuai skema. Data tidak dihapus.','struktur','Sinkronkan'],['Bersihkan cache aplikasi','Memaksa data kegiatan dibaca ulang dari Sheets.','cache','Bersihkan']].map(([a,b,o,l])=>`<div class="row" style="border-top:1px solid var(--b);padding-top:10px"><div><b>${a}</b><br><small class="mut">${b}</small></div><button class="btn" style="background:#EF4444" onclick="ask('${a}?',()=>act('aSistem',{op:'${o}'},'pengaturan'),'${l}')">${l}</button></div>`).join('')}`;
return `<h1>Pengaturan Sistem & Integrasi Workspace</h1><div class="pset"><div class="card pad sn">${T.map((t,i)=>`<a class="${i==PS?'on':''}" onclick="PS=${i};admin('pengaturan')">${t}</a>`).join('')}<a class="${PS==5?'on':''}" style="color:#EF4444" onclick="PS=5;admin('pengaturan')">⚠ Zona Bahaya</a></div><div class="card pad" ${PS==5?'style="border-color:#EF4444"':''}>${PS==5?dz:sec[PS]}</div></div>`}};
async function admin(v='dashboard',id=''){const tk=sessionStorage.tk;if(!tk){location.hash='#/login';return}
if(!window.__adt||Date.now()-window.__adt>60000||!AD.kegiatan){const r=await get('adminData',{token:tk});if(!r.success){sessionStorage.removeItem('tk');toast(r.message,'err');location.hash='#/login';return}AD=r.data;window.__adt=Date.now()}
if(!AD.kegiatan.find(k=>k.id==KID))KID=(AD.kegiatan[0]||{}).id||'';
const M=[['dashboard','▦ Dashboard'],['kegiatan','📅 Kelola Kegiatan'],['peserta','👥 Manajemen Peserta'],['presensi','✔ Presensi & Kehadiran'],['evaluasi','💬 Evaluasi & Kuesioner'],['sertifikat','🏅 E-Sertifikat Digital'],['laporan','📈 Laporan & Ekspor'],['pengaturan','⚙ Pengaturan Sistem']],pend=AD.sertifikat.filter(s=>s.status==='Terbit'&&!s.pdf).length,cur=V[v]?v:(v==='form'?'kegiatan':'dashboard');
const body=await(V[v]||V.dashboard)(id);
app().innerHTML=`<div class="layout"><aside class="sb" id="sb"><b>🛡 SIEVENT<br><small style="font-weight:400;opacity:.7">Admin Panel Kaltim</small></b>${M.map(([k,t])=>`<a href="#/admin/${k}" class="${k===cur?'on':''}" onclick="$('#sb').classList.remove('open')">${t}${k==='sertifikat'&&pend?` <i class="pill amber" style="font-style:normal">${pend}</i>`:''}</a>`).join('')}<a href="#/login" onclick="sessionStorage.removeItem('tk')">⎋ Keluar</a></aside><section style="min-width:0"><div class="top"><span><button class="btn ghost ham" onclick="$('#sb').classList.toggle('open')">☰</button> <b>${(M.find(m=>m[0]===cur)||[])[1]||''}</b></span><span class="mut"><button class="btn ghost" style="padding:6px 10px" onclick="tema()">🌓</button> 🔔${pend?` <i class="pill amber" style="font-style:normal">${pend}</i>`:''} &nbsp;<i class="pill green" style="font-style:normal">AD</i> Administrator</span></div><div class="main">${body}</div></section></div>`}

async function xlsx(h,r,n){if(!window.XLSX)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';s.onload=ok;s.onerror=()=>no(Error('Gagal memuat pustaka Excel (butuh internet)'));document.head.append(s)});
const c=v=>typeof v==='number'?v:String(v).replace(/<[^>]*>/g,''),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([h,...r].map(a=>a.map(c))),'Data');XLSX.writeFile(wb,n+'.xlsx')}
function ovr(id){mdl('Verifikasi Presensi Manual oleh Administrator',`<div class="info amber"><b>OPERATOR OVERRIDE</b> — gunakan hanya jika peserta mengalami kendala teknis. Tercatat pada log audit.</div><label>Alasan Override Kehadiran *</label>${['Kamera / QR rusak','Kendala sinyal / IP','Dispensasi tugas panitia'].map((x,i)=>`<label class="opt"><input type="radio" name="alasan" value="${x}" ${i?'':'checked'}> ${x}</label>`).join('')}<label>Meja Petugas Verifikator *</label><input name="meja" required placeholder="Contoh: Meja Registrasi 01"><label class="opt"><input type="checkbox" required> Saya telah memverifikasi identitas fisik peserta dan menjamin kebenaran kehadirannya.</label>`,d=>act('aPeserta',{op:'hadir',id,alasan:d.alasan,meja:d.meja},'presensi'),'Konfirmasi Presensi Valid (WITA)')}
function bcast(){mdl('Broadcast ke Peserta Terdaftar',`<label>Kegiatan</label><select name="id_kegiatan">${AD.kegiatan.map(k=>`<option value="${k.id}" ${k.id==KID?'selected':''}>${esc(k.nama)}</option>`).join('')}</select><label>Subjek (email)</label><input name="subjek" required maxlength="150"><label>Pesan</label><textarea name="pesan" rows="5" required maxlength="2000"></textarea><button type="button" class="btn ghost full" style="margin-top:8px" onclick="waList()">💬 Buka daftar tautan WhatsApp</button><p class="cap">Email memakai kuota harian Gmail yang sama dengan pengiriman sertifikat (20 dicadangkan, maks 100 per broadcast).</p>`,d=>act('aBroadcast',d,'peserta'),'Kirim Email')}
function waList(){const f=$('#mf'),t=encodeURIComponent(f.pesan.value||''),L=AD.peserta.filter(p=>p.id_kegiatan==f.id_kegiatan.value&&p.status_pendaftaran==='Terdaftar');
f.querySelector('.wal')?.remove();f.insertAdjacentHTML('beforeend',`<div class="info wal" style="max-height:160px;overflow:auto">${L.map(p=>{let n=String(p.no_hp).replace(/\D/g,'');if(n[0]==='0')n='62'+n.slice(1);return `<div><a target="_blank" href="https://wa.me/${n}?text=${t}">💬 ${esc(p.nama_lengkap)}</a></div>`}).join('')||'Tidak ada peserta terdaftar'}</div>`)}
function addAdm(){mdl('Tambah Akun Administrator',`<label>Nama Lengkap</label><input name="nama" required><label>Username (huruf kecil/angka)</label><input name="username" required><label>Kata sandi (min. 8)</label><input type="password" name="password" required><label>Ulangi kata sandi</label><input type="password" name="ulang" required>`,d=>act('aAdmin',{op:'add',...d},'pengaturan'))}

function tpl(){const f=$('#ef');if(!f||!$('#tpv'))return;const l=f.sumber_template_sertifikat.value==='Link',mm=String(f.link_template.value).match(/\/d\/([\w-]+)/),key=l+(mm?mm[1]:''),b=$('#tpv');if(b.dataset.k===key)return;b.dataset.k=key;
b.innerHTML=l&&mm?`<iframe src="https://docs.google.com/presentation/d/${mm[1]}/embed" style="width:100%;aspect-ratio:16/9;border:0;border-radius:12px"></iframe><p class="cap"><span>Pratinjau Slides kustom</span><span>Jika kosong, bagikan sebagai "Siapa saja dengan tautan (Viewer)"</span></p>`:certBox({nama:'{{nama}}',kegiatan:'{{kegiatan}}',nomor:'{{nomor}}',kode:'{{kode}}'})+'<p class="cap"><span>Pratinjau Template Standar SIEVENT</span><span>Landscape 16:9 ✓</span></p>'}
async function imporZoom(i){const f=i.files[0];if(!f)return;const t=await f.text(),em=[...new Set((t.match(/[^\s,;"<>]+@[^\s,;"<>]+\.[^\s,;"<>]+/g)||[]).map(x=>x.toLowerCase()))];if(!em.length)return toast('Tidak ada email pada berkas','err');
ask(`Tandai hadir peserta terdaftar yang emailnya ada di berkas (${em.length} email ditemukan)? Waktu hadir dicatat sebagai waktu impor.`,()=>act('aPeserta',{op:'impor',id_kegiatan:KID,emails:em},'presensi'),'Impor Kehadiran')}

async function comp(f,W=1280){const i=await new Promise((ok,no)=>{const m=new Image;m.onload=()=>ok(m);m.onerror=()=>no(Error('Berkas bukan gambar valid'));m.src=URL.createObjectURL(f)}),s=Math.min(1,W/i.width),c=document.createElement('canvas');c.width=Math.round(i.width*s);c.height=Math.round(i.height*s);c.getContext('2d').drawImage(i,0,0,c.width,c.height);
let b=await new Promise(r=>c.toBlob(r,'image/webp',.8));if(!b||b.type!=='image/webp')b=await new Promise(r=>c.toBlob(r,'image/jpeg',.8));return new Promise(ok=>{const r=new FileReader();r.onload=()=>ok({b:r.result.split(',')[1],t:b.type});r.readAsDataURL(b)})}
