// ===== SIEVENT — Halaman publik tambahan: tema gelap, evaluasi dinamis, pembatalan =====
try{document.documentElement.dataset.theme=localStorage.tema||''}catch(e){}
function tema(){const d=document.documentElement,n=d.dataset.theme==='dark'?'':'dark';d.dataset.theme=n;try{localStorage.tema=n}catch(e){}}
function tb(a,i){a.parentNode.querySelectorAll('a').forEach((x,j)=>x.className=j==i?'on':'');[0,1,2,3].forEach(j=>{const p=$('#p'+j);if(p)p.hidden=j!=i})}
const inp=q=>{const t=q.tipe;
if(t==='Skala 1-5')return `<div class="scale">${[1,2,3,4,5].map(n=>`<button type="button" data-v="${n}">${n}</button>`).join('')}</div>`;
if(t==='Rating Bintang')return `<div class="stars">${[1,2,3,4,5].map(n=>`<span data-v="${n}">★</span>`).join('')}</div>`;
if(t==='Pilihan')return `<div class="f2">${String(q.opsi).split('|').map(o=>`<label class="opt"><input type="radio" name="r${esc(q.id_pertanyaan)}" value="${esc(o)}"> ${esc(o)}</label>`).join('')}</div>`;
return `<textarea maxlength="500" placeholder="Tulis jawaban Anda..."></textarea><small class="cap"><span>0 / 500</span></small>`};
async function evaluasi(id,em=''){const e=(await get('getEvent',{id})).data,Q=(await get('getQuestions',{id})).data||[],A={},wj=q=>String(q.wajib).toUpperCase()==='TRUE';
app().innerHTML=nav('kegiatan')+`<main class="wrap"><form class="card form" id="fr"><div class="tabs"><a>1. Presensi ✓</a><a class="on">2. Evaluasi & Rating</a><a>3. E-Sertifikat</a></div><div class="info"><b>Syarat E-Sertifikat:</b> pengisian evaluasi bersifat wajib. ${esc(e?.nama)}</div><label>Email terdaftar *</label><input type="email" name="email" required value="${esc(decodeURIComponent(em))}">${Q.map((q,i)=>`<div class="q" data-id="${esc(q.id_pertanyaan)}"><b>Q${i+1}. ${esc(q.teks_pertanyaan)} ${wj(q)?'<span style="color:#EF4444">*</span>':''}</b><div style="margin-top:8px">${inp(q)}</div></div>`).join('')}<div class="ftr" id="prog"></div><button class="btn gold full" style="padding:14px">Kirim Evaluasi & Proses E-Sertifikat →</button></form></main>`+foot();
const prog=()=>$('#prog').textContent=`${Object.values(A).filter(x=>String(x).trim()).length} dari ${Q.length} pertanyaan terjawab`;prog();
const set=(el,v)=>{const q=el.closest('.q');A[q.dataset.id]=v;q.querySelectorAll('.scale [data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v==v));q.querySelectorAll('.stars [data-v]').forEach(b=>b.classList.toggle('on',+b.dataset.v<=+v));prog()};
$('#fr').onclick=x=>{const b=x.target.closest('[data-v]');if(b)set(b,b.dataset.v)};
$('#fr').oninput=x=>{const t=x.target;if(t.matches('textarea')){set(t,t.value);t.nextElementSibling.firstChild.textContent=t.value.length+' / 500'}if(t.matches('[type=radio]'))set(t,t.value)};
$('#fr').onsubmit=ev=>kirim(ev,async d=>{const m=Q.find(q=>wj(q)&&!String(A[q.id_pertanyaan]||'').trim());if(m)throw Error('Lengkapi pertanyaan wajib: '+m.teks_pertanyaan);
const r=await post('evaluate',{id_kegiatan:id,email:d.email,jawaban:A});if(!r.success)throw Error(r.message);toast('Evaluasi terkirim! Sertifikat sedang diproses.');location.hash='#/sertifikat'})}
async function batal(id){const e=(await get('getEvent',{id})).data;
app().innerHTML=nav('kegiatan')+`<main class="wrap"><form class="card form" id="fr" style="max-width:560px"><h2>Cek & Batalkan Pendaftaran</h2><p class="mut">${esc(e?.nama)}</p><div class="info">Langkah 1 dari 2 — verifikasi email yang Anda daftarkan.</div><label>Email terdaftar *</label><input type="email" name="email" required><button class="btn full" style="margin-top:16px">Cek Pendaftaran Saya</button></form></main>`+foot();
$('#fr').onsubmit=ev=>kirim(ev,async d=>{const r=await post('cekReg',{...d,id_kegiatan:id});if(!r.success)throw Error(r.message);const v=r.data;
$('#fr').innerHTML=`<h2>Pendaftaran Ditemukan</h2><div class="info"><small class="mut">Peserta</small><br><b>${esc(v.nama)}</b><br><small class="mut">Status</small><br>${v.status==='Waiting'?'<span class="pill amber">Waiting List</span>':'<span class="pill green">Terdaftar</span>'} · <small>Daftar: ${esc(v.waktu)} WITA</small></div>${v.bisa?`<p>Langkah 2 dari 2 — pembatalan akan <b>membebaskan kuota</b> dan tidak dapat diurungkan.</p><button type="button" class="btn full" style="background:#EF4444" id="ok">Ya, Batalkan Pendaftaran</button><a class="btn ghost full" style="margin-top:8px" href="#/detail/${id}">Kembali</a>`:`<div class="info amber">${esc(v.alasan||'Pendaftaran tidak dapat dibatalkan')}</div><a class="btn ghost full" href="#/detail/${id}">Kembali</a>`}`;
if(v.bisa)$('#ok').onclick=async()=>{const z=await post('cancelReg',{...d,id_kegiatan:id});toast(z.message,z.success?'':'err');if(z.success)location.hash='#/kegiatan'}})}

async function drawQR(){const els=[...document.querySelectorAll('.qr:empty')];if(!els.length||window.__qrx)return;
if(!window.qrcode)await new Promise(ok=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcode-generator/1.4.4/qrcode.min.js';s.onload=ok;s.onerror=()=>{window.__qrx=1;ok()};document.head.append(s)});
if(!window.qrcode)return;els.forEach(e=>{const q=qrcode(0,'M');q.addData(e.dataset.u||location.href.split('#')[0]+'#/cek/'+e.dataset.q);q.make();e.innerHTML=q.createSvgTag(3,0)})}
if(typeof MutationObserver!=='undefined')new MutationObserver(()=>{if(document.querySelector('.qr:empty'))drawQR()}).observe(document.body,{childList:true,subtree:true});
async function kiosk(id){clearInterval(window.CD);const e=(await get('getEvent',{id})).data||{};
app().innerHTML=`<div style="min-height:100vh;background:linear-gradient(135deg,var(--pd),var(--p));color:#fff;display:grid;place-items:center;text-align:center;padding:24px"><div><span class="pill amber">KIOSK PRESENSI · MEJA LURING</span><h1 style="color:#fff;margin-top:12px">${esc(e.nama)}</h1><p>Pindai QR dengan kamera ponsel untuk presensi · ${esc(e.presensi_buka||'')} – ${esc(e.presensi_tutup||'')} WITA</p><div style="background:#fff;padding:16px;border-radius:16px;display:inline-block"><span class="qr big" data-u="${location.href.split('#')[0]}#/presensi/${esc(id)}"></span></div><p><small>Jika QR tidak terbaca, buka ${esc(location.host)} → Kegiatan → Isi Daftar Hadir</small></p></div></div>`}
